[package]
name = "gameiguess"
version = "0.1.0"
edition = "2021"

[dependencies]
miniquad = "0.4.7"
glam = "0.29.2"
noise = "0.9.0"
serde_json = "1.0.134"
rand = "0.8.5"
image = "0.25.5"
rayon = "1.10.0"